#title in header
title: "Davis' Alt Notes"

#main info
#owner
# owner: "I am Davis."
# email: test@test.test
# info: "A Master of IT student."
#description
# desc: "I am taking some navie notes here."

#menu
menu:
  Posts: /archives
  Links: /links
  About: /about
  MAIN ver.: //momok.xyz

#index/main page max show posts (in number)
max_post: 5

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Melbourne
placelink: https://en.wikipedia.org/wiki/Melbourne
github: https://github.com/kongwy
linkedin: https://linkedin.com/in/davis-weiyi-kong/
# twitter: https://twitter.com/adisaktijrs
# instagram: https://instagram.com/adisaktijrs

# Misc
nanobar: /js/nanobar.min.js
switch_light: 🌝
switch_dark: 🌚

# favicon
favicon: /images/favicon.png
# thumbnail
# thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: true
disqus_shortname: momok-notes
